packages:
  - backend
  - backend/contracts
  - frontend/web
  - frontend/mobile
  - frontend/packages/*
onlyBuiltDependencies:
  - argon2
  - esbuild
  - "@nestjs/core"
  - "@swc/core"
  - msgpackr-extract
