export * from './common';
export * from './modules';
export * from './permissions';
export * from './events';
export * as Auth from './auth';
export * as Org from './org';
export * as People from './people';
export * as Academics from './academics';
export * as Attendance from './attendance';
export * as Fees from './fees';
export * as Exams from './exams';
export * as Comms from './comms';
export * as Transport from './transport';
export * as Messenger from './messenger';
export * as WhatsApp from './whatsapp';
export * as Cms from './cms';
export * as Crm from './crm';
export * as Billing from './billing';
export { DEFAULT_ROUTING, URGENT_EVENTS, type RoutingChannels } from './comms';
export * from './authz/catalogue';
export * from './authz/engine';
export * from './authz/templates';
export * from './cms-blocks';
