/**
 * Config-driven admin screens for simple records (config over code — docs/02 principles).
 * Each entry maps a console URL /app/r/<key> to an API CRUD endpoint and the fields to show/edit.
 */
export type Field = { key: string; label: string; type?: 'text' | 'number' | 'date' | 'select' | 'money' | 'bool'; options?: string[]; required?: boolean; list?: boolean };
export interface Resource { title: string; api: string; fields: Field[]; create?: boolean }
export const RESOURCES: Record<string, Resource> = {
  staff: { title: 'Staff', api: '/people/staff', create: false, fields: [{ key: 'employeeCode', label: 'Code', list: true }, { key: 'name', label: 'Name', list: true }, { key: 'phone', label: 'Phone', list: true }, { key: 'designation', label: 'Designation', list: true }, { key: 'status', label: 'Status', list: true }] },
  books: { title: 'Library books', api: '/library/books', fields: [{ key: 'title', label: 'Title', required: true, list: true }, { key: 'author', label: 'Author', list: true }, { key: 'isbn', label: 'ISBN', list: true }, { key: 'category', label: 'Category' }, { key: 'rack', label: 'Rack', list: true }] },
  items: { title: 'Inventory items', api: '/inventory/items', fields: [{ key: 'name', label: 'Item', required: true, list: true }, { key: 'category', label: 'Category', list: true }, { key: 'unit', label: 'Unit', list: true }, { key: 'stock', label: 'In stock', list: true, type: 'number' }, { key: 'reorderLevel', label: 'Reorder at', type: 'number' }] },
  suppliers: { title: 'Suppliers', api: '/inventory/suppliers', fields: [{ key: 'name', label: 'Name', required: true, list: true }, { key: 'phone', label: 'Phone', list: true }, { key: 'gstin', label: 'GSTIN', list: true }] },
  visitors: { title: 'Visitor book', api: '/front-office/visitors', fields: [{ key: 'name', label: 'Name', required: true, list: true }, { key: 'phone', label: 'Phone', required: true, list: true }, { key: 'purpose', label: 'Purpose', required: true, list: true }, { key: 'meetWith', label: 'Meeting', list: true }, { key: 'inAt', label: 'In', type: 'date', list: true }] },
  enquiries: { title: 'Enquiries', api: '/front-office/enquiries', fields: [{ key: 'name', label: 'Name', required: true, list: true }, { key: 'phone', label: 'Phone', required: true, list: true }, { key: 'forClass', label: 'Class', list: true }, { key: 'note', label: 'Note' }, { key: 'status', label: 'Status', list: true }] },
  complaints: { title: 'Complaints', api: '/front-office/complaints', fields: [{ key: 'name', label: 'Name', required: true, list: true }, { key: 'category', label: 'Category', required: true, list: true }, { key: 'description', label: 'Description', required: true }, { key: 'status', label: 'Status', type: 'select', options: ['open', 'in_progress', 'resolved', 'closed'], list: true }] },
  hostels: { title: 'Hostels', api: '/hostel/hostels', fields: [{ key: 'name', label: 'Name', required: true, list: true }, { key: 'kind', label: 'Type', type: 'select', options: ['boys', 'girls', 'mixed'], list: true }] },
  vehicles: { title: 'Vehicles', api: '/transport/vehicles', fields: [{ key: 'regNo', label: 'Registration', required: true, list: true }, { key: 'name', label: 'Name', list: true }, { key: 'capacity', label: 'Capacity', type: 'number', required: true, list: true }] },
  'fee-heads': { title: 'Fee heads', api: '/fees/heads', fields: [{ key: 'name', label: 'Name', required: true, list: true }, { key: 'code', label: 'Code', list: true }] },
  subjects: { title: 'Subjects', api: '/academics/subjects', fields: [{ key: 'name', label: 'Name', required: true, list: true }, { key: 'code', label: 'Code', list: true }, { key: 'type', label: 'Type', type: 'select', options: ['theory', 'practical', 'co_scholastic'], list: true }] },
  events: { title: 'Calendar', api: '/calendar/events', fields: [{ key: 'title', label: 'Title', required: true, list: true }, { key: 'kind', label: 'Kind', type: 'select', options: ['holiday', 'event', 'ptm', 'exam', 'vacation'], list: true }, { key: 'startsOn', label: 'From', type: 'date', required: true, list: true }, { key: 'endsOn', label: 'To', type: 'date', required: true, list: true }] },
  alumni: { title: 'Alumni', api: '/alumni/records', fields: [{ key: 'name', label: 'Name', required: true, list: true }, { key: 'batchYear', label: 'Batch', type: 'number', required: true, list: true }, { key: 'occupation', label: 'Occupation', list: true }, { key: 'city', label: 'City', list: true }] },
  batches: { title: 'Batches', api: '/coaching/batches', fields: [{ key: 'name', label: 'Name', required: true, list: true }, { key: 'courseName', label: 'Course', list: true }, { key: 'centre', label: 'Centre', list: true }, { key: 'feePaise', label: 'Fee', type: 'money', list: true }] },
};
