import type { ExpoConfig } from 'expo/config';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/**
 * White-label flavours (docs/02 §11). One codebase, many apps:
 *   FLAVOUR=aadhyay            → common "Aadhyay" app with institution picker
 *   FLAVOUR=<tenant-slug>      → institution-locked app with its own name, icon, package id, colours, signing key
 * Config lives in flavours/<slug>/flavour.json (generated by `pnpm flavour:pull <slug>` from the control plane).
 */
const flavour = process.env.FLAVOUR ?? 'aadhyay';
const dir = join(__dirname, 'flavours', flavour);
if (!existsSync(join(dir, 'flavour.json'))) throw new Error(`Unknown flavour "${flavour}" — create flavours/${flavour}/flavour.json`);
const f = JSON.parse(readFileSync(join(dir, 'flavour.json'), 'utf8'));
const asset = (n: string) => `./flavours/${flavour}/${n}`;
const apiBaseUrl = process.env.API_URL ?? f.apiBaseUrl;
const realtimeUrl = process.env.REALTIME_URL ?? f.realtimeUrl;

const config: ExpoConfig = {
  name: f.name,
  slug: f.slug,
  scheme: f.slug.replace(/[^a-z0-9]/g, ''),
  version: '1.0.0',
  orientation: 'portrait',
  icon: asset('icon.png'),
  userInterfaceStyle: 'automatic',
  android: {
    package: f.android.package,
    adaptiveIcon: { foregroundImage: asset('adaptive-icon.png'), backgroundColor: f.colors.primary },
    permissions: ['ACCESS_FINE_LOCATION', 'ACCESS_BACKGROUND_LOCATION', 'FOREGROUND_SERVICE', 'FOREGROUND_SERVICE_LOCATION', 'CAMERA', 'RECORD_AUDIO', 'READ_CONTACTS', 'POST_NOTIFICATIONS'],
    intentFilters: [{ action: 'VIEW', autoVerify: true, data: (f.deepLinkHosts as string[]).map((h) => ({ scheme: 'https', host: h, pathPrefix: '/track' })), category: ['BROWSABLE', 'DEFAULT'] }],
  },
  ios: {
    bundleIdentifier: f.ios.bundleIdentifier,
    supportsTablet: true,
    associatedDomains: (f.deepLinkHosts as string[]).map((h) => `applinks:${h}`),
    infoPlist: {
      NSLocationWhenInUseUsageDescription: 'Drivers share the bus location with parents during school trips.',
      NSLocationAlwaysAndWhenInUseUsageDescription: 'Bus location keeps updating while the trip is running, even with the screen off.',
      NSCameraUsageDescription: 'Video calls and scanning ID-card QR codes.',
      NSMicrophoneUsageDescription: 'Voice and video calls in Aadhyay Messenger.',
      NSContactsUsageDescription: 'Find people you know on Aadhyay Messenger. Numbers are never stored in plain text.',
      UIBackgroundModes: ['location', 'remote-notification', 'voip'],
    },
  },
  plugins: [
    'expo-router',
    ['expo-splash-screen', { image: asset('splash.png'), imageWidth: 200, resizeMode: 'contain', backgroundColor: f.colors.primary }],
    'expo-secure-store',
    ['expo-location', { isAndroidBackgroundLocationEnabled: true, isAndroidForegroundServiceEnabled: true }],
    'expo-notifications',
    ['expo-build-properties', { android: { minSdkVersion: 26 }, ios: { deploymentTarget: '16.4' } }],
  ],
  experiments: { typedRoutes: false },
  extra: {
    flavour: f.slug,
    tenantSlug: f.tenantSlug,
    apiBaseUrl,
    realtimeUrl,
    colors: f.colors,
    eas: { projectId: process.env.EAS_PROJECT_ID },
  },
};
export default config;
